### ISSUE TITLE
Add filter to run tool on specific files instead of whole repo

### ISSUE THREAD

**Issue by acumino** [joelanford/go-apidiff#14]
Currently, `go-apidiff` internally checkouts to given commit and compare the `git diff`  and the uses `apidiff` to report incompatible changes.
There are chances when users don't want to run `apidiff` on the whole repo and instead only on some specific files because only those are the ones being used by external sources. The exported methods, interface, etc which are internally consumed need not to reported as incompatible changes and therefore should not fail the apidiff changes test.

As of now, this is not possible. Is it possible to have this feature in the future where we can give a list of files in args?

**Comment by joelanford** [comment]
go-apidiff is meant to report breaking API changes for anything that could possibly be consumed externally based on the rules the Go compiler enforces. Anything not meant to be consumed externally should be moved into an `internal` tree on your repo, at which point go-apidiff will ignore it.
