### ISSUE TITLE
Update dependencies to support go 1.18

### ISSUE THREAD

**Issue by AlmogBaku** [joelanford/go-apidiff#15]
The dependencies are somewhat outdated, especially `golang.org/x/tools` which is broken on go 1.18,

@joelanford Can you please release a new version with updated deps?

**Comment by camilamacedo86** [comment]
Hi @AlmogBaku, 

The apidiff on Kubebuilder is only used in the Ci - Github Action
 We can still using go 1.17 for its ci if the appdiff does not work with https://github.com/kubernetes-sigs/kubebuilder/pull/2561/files#diff-dd565f122600dd57c8c3c546dd80893fe3e96c09f41ef16886f908d6d0ce7b50R21
